# Generated by Django 3.0.2 on 2020-02-17 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billCustomerId', models.IntegerField()),
                ('billTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 13, 6, 561385, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryRoot', models.IntegerField(default=0)),
                ('categoryTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 13, 6, 561385, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50, null=True)),
                ('customerPhone', models.IntegerField()),
                ('customerAddress', models.TextField(null=True)),
                ('customerEmail', models.EmailField(max_length=254, null=True)),
                ('customerTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 13, 6, 560388, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCategoryId', models.IntegerField(default=0)),
                ('itemName', models.CharField(max_length=50)),
                ('itemStatus', models.IntegerField(choices=[(0, 'ByMass'), (1, 'ByWeight')], default=0)),
                ('itemStock', models.FloatField()),
                ('itemAlertVal', models.FloatField()),
                ('itemPurchasePrice', models.FloatField()),
                ('itemSellingPrice', models.FloatField()),
                ('itemTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 13, 6, 561385, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transStatement', models.TextField()),
                ('transStatus', models.IntegerField()),
                ('transBillId', models.IntegerField(null=True)),
                ('transAmount', models.IntegerField()),
                ('transTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 13, 6, 561385, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldItemVol', models.FloatField()),
                ('soldPrice', models.FloatField()),
                ('soldTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 13, 6, 561385, tzinfo=utc))),
                ('soldBillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Bills')),
                ('soldItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payTotal', models.IntegerField()),
                ('paymentGot', models.IntegerField()),
                ('payBack', models.IntegerField()),
                ('payTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 17, 13, 6, 561385, tzinfo=utc))),
                ('payBillId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.Bills')),
            ],
        ),
    ]
