# Generated by Django 3.0.2 on 2020-02-19 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 1, 56, 55, 248743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryRoot',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 1, 56, 55, 248743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 1, 56, 55, 248743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 1, 56, 55, 248743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 1, 56, 55, 248743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='soldTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 1, 56, 55, 248743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 1, 56, 55, 248743, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Karts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kartItemVol', models.FloatField()),
                ('kartItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Items')),
            ],
        ),
    ]
