# Generated by Django 3.0.2 on 2020-02-19 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20200219_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 19, 42, 22, 737891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 19, 42, 22, 737891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 19, 42, 22, 737891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemStatus',
            field=models.IntegerField(choices=[(0, 'ByMass'), (1, 'ByUnit')], default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 19, 42, 22, 737891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 19, 42, 22, 737891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='soldTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 19, 42, 22, 737891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transBillId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Bills'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 19, 42, 22, 737891, tzinfo=utc)),
        ),
    ]
