# Generated by Django 3.0.2 on 2020-02-20 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20200220_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 12, 16, 45, 187181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 12, 16, 45, 187181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 12, 16, 45, 187181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 12, 16, 45, 187181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='soldTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 12, 16, 45, 187181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transStatement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transStatus',
            field=models.IntegerField(choices=[(0, 'deposit'), (1, 'withdraw')], default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 12, 16, 45, 187181, tzinfo=utc)),
        ),
    ]
