# Generated by Django 3.0.2 on 2020-02-20 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_auto_20200220_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 56, 59, 57213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 56, 59, 56215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 56, 59, 56215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 56, 59, 57213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='soldTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 56, 59, 57213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transBillId',
            field=models.IntegerField(null=True, verbose_name=myApp.models.Bills),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 56, 59, 57213, tzinfo=utc)),
        ),
    ]
