# Generated by Django 3.0.2 on 2020-03-03 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_auto_20200220_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldItems',
        ),
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 6, 23, 877204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 6, 23, 875704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 6, 23, 875833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 6, 23, 878202, tzinfo=utc)),
        ),
    ]
