# Generated by Django 3.0.2 on 2020-03-03 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_auto_20200303_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 8, 37, 463458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 8, 37, 462462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 8, 37, 462462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 8, 37, 463458, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('soldId', models.IntegerField(primary_key=True, serialize=False)),
                ('soldItemStatus', models.IntegerField(default=0)),
                ('soldItemVol', models.FloatField()),
                ('soldPrice', models.IntegerField()),
                ('soldTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 8, 37, 463458, tzinfo=utc))),
                ('soldBillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Bills')),
                ('soldItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Items')),
            ],
        ),
    ]
