# Generated by Django 3.0.2 on 2020-03-03 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_auto_20200303_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditems',
            name='soldItemStatus',
        ),
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 10, 37, 504433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 10, 37, 502406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 10, 37, 503436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='soldTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 10, 37, 504433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 10, 37, 504433, tzinfo=utc)),
        ),
    ]
