# Generated by Django 3.0.2 on 2020-03-03 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_auto_20200303_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 12, 11, 321558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 12, 11, 320561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 12, 11, 321558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='soldTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 12, 11, 321558, tzinfo=utc)),
        ),
    ]
