# Generated by Django 3.0.2 on 2020-03-03 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_auto_20200303_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 13, 47, 292484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 13, 47, 290456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 13, 47, 291485, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='soldTimeOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 13, 47, 292484, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transId', models.IntegerField(primary_key=True, serialize=False)),
                ('transStatement', models.TextField(null=True)),
                ('transStatus', models.IntegerField(choices=[(0, 'deposit'), (1, 'withdraw')], default=0)),
                ('transAmount', models.IntegerField()),
                ('transTimeOfCreation', models.DateTimeField(default=datetime.datetime(2020, 3, 3, 12, 13, 47, 292484, tzinfo=utc))),
                ('transBillId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.Bills')),
            ],
        ),
    ]
